GoogleCloudPlatform/gcs-fuse-csi-driver

- go.mod
- pkg/webhook/mutatingwebhook_test.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
- vendor/modules.txt
Created unit tests for the mutatingwebhook.go, which houses the core logic for admission request handling.
> Added unit tests for mutatingwebhook.go

- cmd/sidecar_mounter/gcsfuse_binary
(cherry picked from commit aa49f10779c3c774770bbe71b10616adabec39c1)
> Cherrypick #298 to release-1.4 

- cmd/sidecar_mounter/gcsfuse_binary
> Cherrypick #301 to release-1.4

- pkg/metrics/metrics.go
- pkg/sidecar_mounter/sidecar_mounter.go
Prevent race condition between reading and writing at the same time.
> Handle read while writing race condition.

- pkg/metrics/metrics.go
- pkg/sidecar_mounter/sidecar_mounter.go
Use os.rename to read/write to metrics file without race conditions.
We want to make sure that we do not modify the metrics file once written as the can be another process reading the file. To get around this, we will employ the use of os.rename, an atomic operation in unix. We will first write the latest sample of the metrics to a temporary file. After we finish writing, we will rename the file, and put a higher generation number in the file name to signify this is the latest file. 
We will also clean up files that are 2 generations older than the most recent to avoid memory increase.
> Use os.rename to read/write to metrics file without race conditions.

- deploy/base/webhook/validating_admission_policy.yaml
Cleanup repetitive logic in ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding
> Simplify VAP annotation check expression.

- cmd/sidecar_mounter/gcsfuse_binary
- deploy/base/webhook/validating_admission_policy.yaml
Cherrypick #357  and #358 to release-1.7
> Cherry #357, #358 to release-1.7

- examples/mitigation-webhook/README.md
- examples/mitigation-webhook/create-cert.sh
- examples/mitigation-webhook/webhook.yaml
> mutating webhook to update gcsfusecsi-node daemonset mem limits

- test/e2e/specs/specs.go
- test/e2e/specs/testdriver.go
- test/e2e/testsuites/failed_mount.go
- test/e2e/testsuites/volumes.go
Fix metadata prefetch e2e tests.
> Fix metadata prefetch e2e tests.

- .github/dependabot.yml
Update dependabot to track vulnerabilities in metadata prefetch sidecar image.
> Update dependabot to track vulnerabilities in metadata prefetch image.

- pkg/cloud_provider/clientset/clientset.go
Filtering informerFactory to return metadata w/o ManagedFields to improve GCSFUSE CSI driver memory usage.
> Filtering informerFactory to return metadata w/o ManagedFields

- pkg/cloud_provider/clientset/clientset.go
Cherry pick of #398 on release-1.8.
#398: Filtering informerFactory to return metadata w/o ManagedFields
```release-note
```
> Automated cherry pick of #398: Filtering informerFactory to return metadata w/o ManagedFields

- test/e2e/testsuites/gcsfuse_integration.go
Add trace logs for gcsfuse integration tests.
> Add debug logs for integration tests.

- test/e2e/testsuites/gcsfuse_integration.go
#426 bump was not sufficient, bumping the mem limit to 5Gi
> increase volume tester pod mem limit

- go.mod
- go.sum
- vendor/golang.org/x/net/LICENSE
- vendor/golang.org/x/net/html/doc.go
- vendor/golang.org/x/net/html/doctype.go
- vendor/golang.org/x/net/html/foreign.go
- vendor/golang.org/x/net/html/iter.go
- vendor/golang.org/x/net/html/node.go
- vendor/golang.org/x/net/html/parse.go
- vendor/golang.org/x/net/http2/client_conn_pool.go
- vendor/golang.org/x/net/http2/config.go
- vendor/golang.org/x/net/http2/config_go124.go
- vendor/golang.org/x/net/http2/config_pre_go124.go
- vendor/golang.org/x/net/http2/frame.go
- vendor/golang.org/x/net/http2/http2.go
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/net/http2/unencrypted.go
- vendor/golang.org/x/net/http2/write.go
- vendor/golang.org/x/net/websocket/websocket.go
- vendor/modules.txt
> bump golang.org/x/net to fix CVE-2024-45338

- test/e2e/testsuites/failed_mount.go
GCSFuse is now more clear about why Mounting failed, which caused GKE testcases to become obsolete. PR created to support InvalidArgument error code as a valid response to wrong bucket name / format.
> Support InvalidArgument Failed Mount description from GCSFuse in e2e Tests

- cmd/sidecar_mounter/gcsfuse_binary
Update gcsfuse_binary to v2.10.0
/cc @amacaskill
> Update gcsfuse_binary to v2.10.0

- pkg/cloud_provider/auth/fake.go
- pkg/cloud_provider/auth/token_manager.go
- pkg/csi_driver/node.go
- pkg/sidecar_mounter/sidecar_mounter.go
- pkg/sidecar_mounter/sidecar_mounter_config.go
- pkg/sidecar_mounter/sidecar_mounter_config_test.go
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
> Add identity provider into mount options

- test/e2e/utils/cluster.go
- test/e2e/utils/handler.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
We need to keep track of the e2e tests that run in the GKE managed driver separately once these changes reach Prod. This has been outdated for a while for some tests. Updating and refactoring.
```release-note
```
> Update e2e tests ran in managed driver.

- renovate.json
/cleanup
```release-note
None
```
> Start testing renovate

- hack/utils/delete-generated-buckets.sh
Redo #500 now that we have fixed issue #458 in PR #503
> Redo "Add script to delete leaked autogenerated buckets."

- cmd/sidecar_mounter/gcsfuse_binary
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Bump GCSFuse to 2.11.1
Fixes #
```release-note
Bump GCSFuse to 2.11.1 
```
> bump gcsfuse to 2.11.1

- cmd/metadata_prefetch/Dockerfile
- cmd/metadata_prefetch/main.go
- hack/boilerplate/boilerplate.Dockerfile.txt
- hack/boilerplate/boilerplate.Makefile.txt
- hack/boilerplate/boilerplate.go.txt
- hack/boilerplate/boilerplate.md.txt
- hack/boilerplate/boilerplate.py
- hack/boilerplate/boilerplate.py.txt
- hack/boilerplate/boilerplate.sh.txt
- hack/boilerplate/boilerplate.yaml.txt
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
New files/code that does not rely on code that originates from Kubernetes Authors should not be marked with this distinction in boilerplate.
Fixes #
/cc @msau42 
```release-note
```
> Remove Kubernetes Authors requirement from boilerplate.

- cmd/sidecar_mounter/gcsfuse_binary
>
/kind bug
> /kind design
> /kind flake
Bump GCSFuse to v2.1.2 to fix CVE-2024-45337 & CVE-2025-22870 
Fixes #
```release-note
Bump GCSFuse to v2.1.2 to fix CVE-2024-45337 & CVE-2025-22870 
```
> Bump GCSFuse to v2.1.2 to fix CVE-2024-45337 & CVE-2025-22870 

- pkg/sidecar_mounter/sidecar_mounter_config.go
- pkg/sidecar_mounter/sidecar_mounter_config_test.go
Reverts GoogleCloudPlatform/gcs-fuse-csi-driver#577
> Revert "Automated cherry pick of #574: Enable metrics collection by default on gcsfusecsi sidecar."

- cmd/sidecar_mounter/gcsfuse_binary
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Bump gcsfuse binary to v2.12.0 as part of GKE/GCSFuse joint release for gcsfuse v2.12.
Fixes #
```release-note
Bump gcsfuse binary to v2.12.0 as part of GKE/GCSFuse joint release for gcsfuse v2.12.
```
> Bump gcsfuse binary to v2.12.0

- cmd/csi_driver/Dockerfile
- cmd/sidecar_mounter/Dockerfile
- cmd/webhook/Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
To fix louhi release flow of v1.5.3. Same issue/fix as https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/568, but for 1.5 branch. 
Fixes #
```release-note
NONE
```
> bump golang to golang:1.23.3

- Makefile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
> Fix sanity tests on presubmit

- pkg/util/util.go
- pkg/util/util_test.go
/kind bug
Currently, the fuse socket consists of the following format: `/sockets/PodUID_VolumeID/sockets`. Customers specifying long volume names can make the path exceed 104 chars, which will lead to`bind: invalid argument` errors: https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blame/eeeb147f62994c559bd423221f2cef72bac68658/pkg/csi_mounter/csi_mounter.go#L211-L215. 
A solution ot this is to change  `/sockets/x/sockets` to be `/sockets/sha1Hash(x)/sockets`. The sha1Hash will always be of 40 chars, which makes the entire string never be longer than 66 chars, fixing this problem.
Fixes # …
> Hash socket name to prevent long socket names from causing issues.

- pkg/util/util.go
- pkg/util/util_test.go
Cherry pick of #582 on release-1.15.
#582: Hash socket name to prevent long socket names from causing issues.
```release-note
Apply hashing to the Fuse socket path to avoid long volumes from exceeding 104 char limit and causing `bind: invalid argument` errors.
```
> Automated cherry pick of #582: Hash socket name to prevent long socket names from causing issues.

- cmd/sidecar_mounter/gcsfuse_binary
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Bump gcsfuse binary to v2.12.1
Fixes #
```release-note
Bump gcsfuse binary to v2.12.1
```
> Bump gcsfuse binary to v2.12.1

- docs/troubleshooting.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
playbook for log-severity gcsfuse cli flag
```
> playbook for log-severity gcsfuse cli flag

- cmd/sidecar_mounter/main.go
- pkg/csi_driver/node.go
- pkg/csi_driver/utils.go
- pkg/csi_mounter/csi_mounter.go
- pkg/sidecar_mounter/sidecar_mounter.go
- pkg/util/util.go
Cherrypick #657 to release-1.15
> Cherrypick #657 to release-1.15: Add support for node restarts.

- cloudbuild-build-image.yaml
- cloudbuild-install.yaml
- docs/development.md
- docs/installation.md
>
> /kind bug
> /kind design
> /kind flake
This allows for customers to use cloudbuild to build and push the driver. It shows how you would do this on a google internal project vs what is needed for non google internal projects, and how you would do this when installing the driver on a GKE cluster vs k8s on gke cluster. 
Fixes #
```release-note
NONE
```
> add cloud build for manually building and installing custom GCSFuse CSI Driver image

- cloudbuild-build-image.yaml
- cloudbuild-install.yaml
- docs/installation.md
…build for k8s on gce
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
> update instructions to remove cluster name and cluster location from cloud build for k8s on gce

- docs/development.md
- docs/installation.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
> update install with worker-pool documentation

- docs/installation.md
>
> /kind bug
> /kind design
> /kind flake
fix typo in worker pool cloud build installation docs
Fixes #
```release-note
NONE
```
> fix typo in worker pool cloud build installation docs

- cloudbuild-uninstall.yaml
- docs/installation.md
>
> /kind bug
> /kind design
> /kind flake
add uninstall cloudbuild script
Fixes #
```release-note
NONE
```
> add uninstall cloudbuild script

- docs/troubleshooting.md
>
> /kind bug
> /kind design
> /kind flake
Add WI check NodePublishVolume failure to troubleshooting guide for customer to get guidance on how to resolve failure.
Fixes #
```release-note
None
```
> Add WI check NodePublishVolume failure to troubleshooting guide.

- docs/authentication.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
v1.17.2 will be cut soon
```release-note
Support hostnetwork enabled pods via pod ksa.
```
> Add hostnetwork support documentation for OSS users

- docs/oss-k8s-e2e-setup.md
>
> /kind bug
> /kind design
> /kind flake
update minimum version for oss k8s support in oss k8s setup guide
Fixes #
```release-note
NONE
```
> update minimum version for oss k8s support in oss k8s setup guide
