GoogleCloudPlatform/gcs-fuse-csi-driver

docs/installation.md, docs/usage.md
Currently, if the user does not specify a tag, the "make deploy" will generate a dirty commit tag that does not exist. In addition, I found a few spelling mistakes I am correcting.
This will close #1
=> add instruction to install guide to use tag

cmd/csi_driver/Dockerfile, deploy/base/controller/controller.yaml, deploy/base/node/node.yaml, deploy/images/stable/image.yaml
Kubernetes is migrating its image registry from [k8s.gcr.io](http://k8s.gcr.io/) to [registry.k8s.io](http://registry.k8s.io/).
Part of kubernetes/k8s.io#4780
=> fix: migrate from k8s.gcr.io to registry.k8s.io

examples/gcsfuse-e2e-test/pod.yaml
Currently, the gcsfuse e2e tests(integration tests) are run from a test branch in gcsfuse repo because the master branch didn't support running the tests on already mounted directory. 
The master branch now supports running the tests from already mounted directory and these changes to shift to using master branch.
=> Run gcsfuse e2e tests from master of gcsfuse repo

examples/gcsfuse-e2e-test/pod.yaml
We introduced--integrationTest flag in [gcsfuse](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/tools/integration_tests/setup/setup.go#L20) for running integration tests.
GODEBUG="asyncpreemptoff=1" go test -v --integrationTest --mountedDirectory="/gcs" (all the tests are running fine with this command)
=> Adding integration test flag

go.mod, release-tools/README.md, release-tools/go-get-kubernetes.sh, test/e2e/specs/specs.go, vendor/modules.txt
add replace statements for k8s.io/kubernetes packages. From https://github.com/kubernetes/kubernetes/#to-start-using-k8s, Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries is not supported. We are using these packages in the test/e2e/specs. 
This caused an issue when trying to add module dependencies for boskos for managed prow tests. See [this comment](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/24#issuecomment-1550367390). This added a lot of files, so I am going to split the managed prow test grid in to two PRs. The first will be updating go.mod file with the replace statements as described in the README. To do this I ran these commands: 
```
sudo chmod +x release-tools/go-get-kubernetes.sh 
./release-tools/go-get-kubernetes.sh …
```
=> Add replace statements for k8s.io/kubernetes packages

docs/installation.md
The e2e tests only pass with --machine-type=n2-standard-4 so adding that here.
=> Update installation step to mention required machine type

pkg/webhook/mutatingwebhook.go
Refactored the webhook validation logic so that the appropriate message is returned.
=> Refactored webhook validation logic.

pkg/webhook/mutatingwebhook.go, pkg/webhook/mutatingwebhook_test.go
When the annotation limit is zero and request is unset, we set request to use the default value.
=> Set resource request to use default when limit annotation is zero.

test/e2e/run-e2e-ci.sh
gcsfuse now requires at least 1.22.2 which is causing our tests to fail. 
gcsfuse pr:
https://github.com/GoogleCloudPlatform/gcsfuse/commit/923987bb58b9ad6180eb16d98e06b74ae8aba8d3
=>  Upgrade go version to 1.22.2

pkg/csi_driver/node.go
Issues:
1. CSI node driver was initializing the storage client on every node publish. This is an expensive call which does a 3-way handshake to k8s API server, STS server, and GCP IAM. 
2. GCSFUse already validates the bucket access during mount init. This makes the CSI node driver checks redundant.
Fix:
remove the bucket access check and the storage client init on every node publish call.
Tests:
1. manually tested on 1.29 cluster, 1.29(master), 1.28(nodepool), success and failure scenarios..
Verified that gcsfuse denies mount request of the SA does not have the necessary permissions on the bucket
```
SetUpBucket: Error in iterating through objects: Get \"https://storage.googleapis.com/storage/v1/b/test-csi-fix/o?alt=json&delimiter=&endOffset=&includeFoldersAsPrefixes=false&includeTrailing …
```
=> Remove Bucket access check from node csi drvier

test/e2e/testsuites/failed_mount.go
With [PR](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/255) the CSI driver no longer checks bucket access, and relies on gcs mount path to perform the check. This means, for the failed mount testcases the failures are now communicated back from the CSI sidecar back to the node driver.  There is change in the reported error codes in node republish. The tester timesout waiting for expected code.
=> fix e2e test failures for failed mount test cases

test/e2e/run-e2e-ci.sh, test/e2e/testsuites/gcsfuse_integration.go, test/e2e/testsuites/gcsfuse_integration_file_cache.go
Cherry pick of #256 on release-1.3.
#256: Update prow tests to go1.22.3
```release-note
```
=> Automated cherry pick of #256: Update prow tests to go1.22.3

test/e2e/testsuites/gcsfuse_integration.go
Cherry pick of #239 on release-1.3.
#239: Increase list_large_dir e2e test timeout.
```release-note
```
=> Automated cherry pick of #239: Increase list_large_dir e2e test timeout.

pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go
In PR #255 we used volumeAttributesToMountOptionsMapping to iterate the expected keys and check for `VolumeContextKeySkipCSIBucketAccessCheck`. This may add confusion to the reader, as this is not strictly a mount option.
Moving the check for the existence of the key in a separate block. 
Address [comment](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/272#issue-2321519510)
=> Remove skip access check from mount options

pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go
There is a typo in the public documentation. This change adds `metadataCacheTtlSeconds` volume attribute support. The existing `metadataCacheTTLSeconds` volume attribute is not changed.
=> support metadataCacheTtlSeconds volume attribute

cmd/csi_driver/Dockerfile, cmd/sidecar_mounter/Dockerfile, cmd/webhook/Dockerfile
=> Cherrypick #288, #286, #285 to release-1.4

cmd/csi_driver/main.go, deploy/base/node/node_setup.yaml, pkg/cloud_provider/clientset/clientset.go, pkg/cloud_provider/clientset/fake.go, pkg/csi_driver/node.go, test/e2e/e2e_test.go
This change refactors `GetPod` function to use Pod informer and lister to get Pod spec. This change avoids direct Pod GET API calls to increase the CSI node driver scalability.
=> use Pod informer to avoid Pod GET API calls

pkg/cloud_provider/storage/fake.go, pkg/cloud_provider/storage/storage.go, pkg/csi_driver/node.go, test/e2e/e2e_test.go, test/e2e/specs/testdriver.go, test/e2e/testsuites/failed_mount.go, test/e2e/utils/handler.go
This change caches NodePublishVolume response state in memory. In the following republish calls, the bucket access check will be skipped if it has ever succeeded. The volume state is cleaned up when the NodeUnpublishVolume is called against the same target path.
This change will completely remove STS API requests, Kube API SA API GET requests, and GCS API Object List requests in the node republish calls.
=> cache NodePublishVolume response state for republish

pkg/webhook/injection.go, pkg/webhook/injection_test.go
This change adds the control plane version check to decide if the gcsfuse sidecar container needs to be a native sidecar container.
=> always check the control plane version to decide native sidecar

Makefile, deploy/base/webhook/manage-validating_admission_policy.sh, deploy/base/webhook/validating_admission_policy.yaml, go.mod, pkg/webhook/validating_admission_policy_test.go
Add a `ValidatingAdmissionPolicy` in 1.30+ clusters.
This `ValidatingAdmissionPolicy` does the following validations:
1. It filters out Pods with an annotation `gke-gcsfuse/volumes: true`, and has a native sidecar container with name `gke-gcsfuse-sidecar`. The validation skips any other unmatched Pods.
2. It checks if the native sidecar container `restartPolicy` is `Always`.
3. It checks if the native sidecar container has env var `NATIVE_SIDECAR: TRUE`.
If there is any errors in the validator, it does not block the Pod creation request because of `failurePolicy: Ignore`.
This change gives users clear error message when the native sidecar container is mutated by other conflicting webhooks.
=> add ValidatingAdmissionPolicy in 1.30 clusters

test/e2e/main.go, test/e2e/specs/istio-service-entry.yaml, test/e2e/specs/istio-sidecar.yaml, test/e2e/specs/specs.go, test/e2e/testsuites/istio.go, test/e2e/utils/handler.go, test/e2e/utils/install-istio.sh
This change adds real istio test cases. The test does the following:
- Install Istio.
- Deploy workloads with istio proxy injected.
- Happy path test: read/write works with the proxy injected, with proper pod annotations, and service entry.
- Failure test: with the pod or service entry missing, we should see specific errors.
We don't rely on or test the sidecar ordering, so removing the sidecar ordering test.
Docs will be updated in follow-up PRs.
=> add istio e2e tests

pkg/metrics/metrics.go
Adding this label to each pod instance allows us to uniquely identify a stream so that we avoid monitoring services from dropping our metrics when we export cumulative values which are lower than last seen by service.
=> Add pod_uid label to handle pod restarts/reschedules.

cmd/csi_driver/main.go, cmd/sidecar_mounter/main.go, deploy/base/node/node.yaml, deploy/overlays/dev/node_pprof.yaml, docs/metrics/metrics.md, docs/metrics/prometheus-values.yaml, go.mod, pkg/csi_driver/gcs_fuse_driver.go, pkg/csi_driver/gcs_fuse_driver_test.go, pkg/csi_driver/node.go, pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go, pkg/metrics/fake.go, pkg/metrics/metrics.go, pkg/sidecar_mounter/sidecar_mounter.go, pkg/sidecar_mounter/sidecar_mounter_config.go, pkg/sidecar_mounter/sidecar_mounter_config_test.go, pkg/util/util.go, test/e2e/e2e_test.go, test/e2e/specs/specs.go, test/e2e/testsuites/metrics.go, test/e2e/utils/handler.go, test/sanity/sanity_test.go
Google Cloud Storage FUSE offers client-side Prometheus metrics for monitoring file system operations and performance. With this change, these metrics, gathered by the sidecar container, are forwarded to the CSI driver node servers. You can access these metrics via a Prometheus server. This guide explains how to enable client-side metrics, set up a Prometheus server, and query the metrics for insights.
=> Add Prometheus metrics support

cmd/webhook/main.go, pkg/cloud_provider/clientset/clientset.go
For core K8s API objects like Pods, Nodes, etc., we can use protobuf encoding which, compared to the default JSON encoding, reduces CPU consumption related to (de)serialization, reduces overall latency of the API calls, reduces memory footprint and the work performed by the GC and results in quicker propagation of objects to event handlers of shared informers.
Core system components of K8s default their serialization method to protobuf for 8 years already: https://github.com/kubernetes/kubernetes/pull/25738.
Some benchmarks comparing JSON vs. protobuf showcasing how the latter data format (de)serializes faster and uses less memory:
- https://medium.com/@akresling/go-benchmark-json-v-protobuf-4ec3c62ec8d4
- https://www.codingexplorations.com/blog/performance-comparison-protobuf-marshaling-v …
=> Use protobuf encoding for core K8s APIs in gcs-fuse-csi-driver

test/e2e/testsuites/gcsfuse_integration.go, test/e2e/testsuites/gcsfuse_integration_file_cache.go, test/e2e/testsuites/gcsfuse_integration_file_cache_parallel_downloads.go
TestGrid is failing with the error below:
``` stderr: go: downloading go1.23.0 (linux/amd64)
go: ../../../go.mod requires go >= 1.23.2 (running go 1.23.0; GOTOOLCHAIN=go1.23.0): 
<exec.CodeExitError>: 
command terminated with exit code 1
push_pin
{
Err: <*errors.errorString | 0xc000202940>{
s: "command terminated with exit code 1",
},
Code: 1,
}
```
=> Bump integration test GOTOOLCHAIN to go1.23.2.

pkg/webhook/injection.go, pkg/webhook/mutatingwebhook.go, pkg/webhook/mutatingwebhook_test.go, pkg/webhook/parsers.go
Some webhooks are not running the latest kubernetes api version. these webhooks do not recognize the native sidecar feature and strip important data from gke-gcsfuse-sidecar spec, causing startup failures. This PR allows the user to manually disable native sidecar injection so that they're able to use these older webhooks. (eg. https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/296)
=> Add annotation to manually enable/disable native sidecar injection.

cmd/csi_driver/Dockerfile, cmd/sidecar_mounter/Dockerfile, cmd/webhook/Dockerfile
Adding this flag fixes a specific issue we observed where attempting to build a linux/ARM64 driver would either time out for several hours or produce the error: `.buildkit_qemu_emulator: /bin/sh: Invalid ELF image for this architecture`.
Adding this line ensures that our build platform is honored in our Dockerfile.
More information about this flag: https://docs.docker.com/build/building/multi-platform/#cross-compilation
=> Add platform flag to Golang binary to honor build platform

cmd/csi_driver/Dockerfile, cmd/sidecar_mounter/Dockerfile, cmd/webhook/Dockerfile
Cherry pick of #368 on release-1.7.
#368: Add platform flag to Golang binary to honor build platform
```release-note
```
=> Automated cherry pick of #368: Add platform flag to Golang binary to honor build platform

cmd/csi_driver/Dockerfile, cmd/sidecar_mounter/Dockerfile, cmd/webhook/Dockerfile
Cherry pick of #368 on release-1.3.
#368: Add platform flag to Golang binary to honor build platform
```release-note
```
=> Manual cherry pick of #368: Add platform flag to Golang binary to honor build platform

test/e2e/specs/specs.go
The test is checking the number of configmaps in the cluster to be 1. It is not checking for the number of configmap.data entries at this point.
=> Revert configmap length check to fix e2e tests

cmd/metadata_prefetch/Dockerfile
Cherry pick of #389 on release-1.8.
#389: Bump golang from 1.22.7 to 1.23.3 in /cmd/metadata_prefetch
```release-note
```
=> Automated cherry pick of #389: Bump golang from 1.22.7 to 1.23.3 in /cmd/metadata_prefetch

cmd/metadata_prefetch/Dockerfile
Currently when trying to build ARM image, we are unable to find the dependencies. 
cc. @saikat-royc 
```
Add ARM dependencies to metadata prefetch Dockerfile.
```
=> Add ARM dependencies to metadata prefetch Dockerfile.

Makefile, cmd/csi_driver/Dockerfile, cmd/metadata_prefetch/Dockerfile, cmd/sidecar_mounter/Dockerfile, cmd/webhook/Dockerfile
Set GOARCH to TARGETPLATFORM to correctly build for ARM machines.
Built using the following command:
```
make build-image-and-push-multi-arch REGISTRY=jaimebz STAGINGVERSION=$TAG BUILD_ARM=true
```
Deployed the built images via the non-managed driver on clusters running different machine architectures.
| Node | Tested |
| --------- | -------|
| amd64 | Pass | 
| arm64 | Pass |
```release-note
Set GOARCH to TARGETPLATFORM to correctly build for ARM machines.
```
=> Set GOARCH through TARGETPLATFORM to correctly build for ARM machines.

Makefile, cmd/csi_driver/Dockerfile, cmd/metadata_prefetch/Dockerfile, cmd/sidecar_mounter/Dockerfile, cmd/webhook/Dockerfile
Cherry pick of #394 on release-1.8.
#394: Set GOARCH through TARGETPLATFORM to correctly build for ARM machines.
```release-note
Set GOARCH to TARGETPLATFORM to correctly build for ARM machines.
```
=> Automated cherry pick of #394: Set GOARCH through TARGETPLATFORM to correctly build for ARM machines.

cmd/metadata_prefetch/Dockerfile
Cherry pick of #391 on release-1.8.
#391: Add ARM dependencies to metadata prefetch Dockerfile.
```release-note
```
=> Automated cherry pick of #391: Add ARM dependencies to metadata prefetch Dockerfile.

test/e2e/e2e_test.go, test/e2e/main.go, test/e2e/run-e2e-ci.sh, test/e2e/specs/testdriver.go, test/e2e/testsuites/gcsfuse_integration.go, test/e2e/testsuites/gcsfuse_integration_file_cache.go, test/e2e/testsuites/gcsfuse_integration_file_cache_parallel_downloads.go, test/e2e/utils/handler.go
Run gRPC protocol for e2e tests.
Subsequent PR contents:
-  Run grpc on any additional functional testsuites
- Run grpc on performance testsuites.
=> Run gRPC e2e integration tests.

test/e2e/testsuites/performance.go
cc. @saikat-royc 
http1 is the default protocol used, so it is safe to remove as it will still be used by default.
=> Remove setting client-protocol for performance tests.

cmd/sidecar_mounter/gcsfuse_binary
This patch does not release new features. Patch addresses the following CVEs:
- CVE-2024-45337
cc. @saikat-royc
=> Update gcsfuse to v2.5.2

cmd/sidecar_mounter/gcsfuse_binary
Cherry pick of #414 on release-1.8.
#414: Update gcsfuse to v2.5.2
```release-note
```
=> Automated cherry pick of #414: Update gcsfuse to v2.5.2

pkg/cloud_provider/clientset/clientset.go
Filtering informerFactory to only return relevant PodSpec information to improve GCSFUSE CSI driver memory usage for pods and deployments with larger Pod Specs.
=> Filtering informerFactory to only return relevant PodSpec information

cmd/csi_driver/Dockerfile, deploy/base/node/node.yaml, pkg/csi_mounter/csi_mounter.go, pkg/csi_mounter/csi_mounter_test.go, test/e2e/e2e_test.go, test/e2e/specs/specs.go, test/e2e/specs/testdriver.go, test/e2e/testsuites/mount.go, test/e2e/utils/handler.go
Support read_ahead_kb and max_ratio configs through mount options.
=> Support read ahead configs through mount options.

pkg/cloud_provider/clientset/clientset.go
In Kubernetes versions that do not support native sidecar, we put an exit file for the sidecar to read once all the containers in the pod have terminated. This behavior partly depends on the RestartPolicy of the Pod. Tracking of this policy was recently removed in #413. Adding it back to Pod.Spec.RestartPolicy in node server pod informer to fix regression in 1.28.
Ran non-managed driver on cluster running GKE v1.28.15-gke.1020000 and verified auto-termination testsuite succeeds.
cc. @saikat-royc @halimsam
=> Track restartPolicy in node pod informer.

test/e2e/run-e2e-ci.sh, test/e2e/run-e2e-local.sh
Pass GCSFUSE_CLIENT_PROTOCOL envVar as a flag to testsuite to support gPRC tests locally.
cc. @saikat-royc
=> Support gPRC tests locally.

test/e2e/testsuites/gcsfuse_integration.go
In the prow test runs, we see a flay behavior for the test cases in the testsuite https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/test/e2e/testsuites/gcsfuse_integration.go
On deeper investigation, we see that the `volume_tester` container downloads various packages and hovers, or exceeds the set limit of 1Gi for memory. [code](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/test/e2e/testsuites/gcsfuse_integration.go#L236)
=> Increase tester pod mem limit to avoid flaky OOM

test/e2e/testsuites/gcsfuse_integration.go
=> Increase sidecar memory limit for gcsfuse integration tests on GKE.

docs/development.md
Removing `BUILD_GCSFUSE_FROM_SOURCE=true` as a requirement to develop the CSI Driver. This should instead be optional, and it is only needed if you are developing CSI on top of a new/unreleased GCSFuse enhancement or feature.
=> Remove BUILD_GCSFUSE_FROM_SOURCE=true dev requrement.

test/e2e/testsuites/gcsfuse_integration.go, test/e2e/testsuites/gcsfuse_integration_file_cache.go, test/e2e/testsuites/gcsfuse_integration_file_cache_parallel_downloads.go
Following up from changes in #430. We are continuing to face flakey behavior on gcsfuse integration testsuite on GKE, this time affecting the remaining gcsfuse integration testsuites. We are increasing the minimum sidecar resource request and limit for all gcsfuse integration test suites to prevent OOM when testing gRPC. We are increasing the requested memory to prevent a sidecar from getting evicted in the event too many pods are bursting at the same time in the same node.
/cc @raj-prince
=> Increase gcsfuse integration e2e test suite sidecar memory request and limits.

go.mod, go.sum, vendor/golang.org/x/net/LICENSE, vendor/golang.org/x/net/html/doc.go, vendor/golang.org/x/net/html/doctype.go, vendor/golang.org/x/net/html/foreign.go, vendor/golang.org/x/net/html/iter.go, vendor/golang.org/x/net/html/node.go, vendor/golang.org/x/net/html/parse.go, vendor/golang.org/x/net/http2/client_conn_pool.go, vendor/golang.org/x/net/http2/config.go, vendor/golang.org/x/net/http2/config_go124.go, vendor/golang.org/x/net/http2/config_pre_go124.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/http2.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/net/http2/unencrypted.go, vendor/golang.org/x/net/http2/write.go, vendor/golang.org/x/net/websocket/websocket.go, vendor/modules.txt
Cherry pick of #441 on release-1.10.
#441: bump golang.org/x/net to fix CVE-2024-45338
```release-note
```
=> Automated cherry pick of #441: bump golang.org/x/net to fix CVE-2024-45338

test/e2e/testsuites/gcsfuse_integration.go, test/e2e/testsuites/gcsfuse_integration_file_cache.go, test/e2e/testsuites/gcsfuse_integration_file_cache_parallel_downloads.go
>  
> /kind api-change  
/kind bug  
> /kind cleanup  
> /kind design  
> /kind documentation  
> /kind failing-test  
> /kind feature  
> /kind flake  
**What this PR does / why we need it**:  
Adds additional step during test to parse  '/gcsfuse/tools/cd_scripts/e2e_test.sh' for the version of go being used by fuse teams integration tests and uses that version to run 
This has been causing issues for the team while running fuse teams integrations tests because whenever fuse team updates their version of go and our versions are not in sync, integration tests fail causing us to have to manually upgrade the version in the command that runs …
=> fuechr/Add automated go version extraction for e2e tests with fuse 

test/e2e/testsuites/gcsfuse_integration.go
Bug fix
**What this PR does / why we need it:**
This is a correction for https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/429 
This change corrects the command to grep go version it is needed because it is causing test failures
**Which issue(s) this PR fixes:**
Fixes # https://buganizer.corp.google.com/issues/379879910
**Special notes for your reviewer:**
n/a
**Does this PR introduce a user-facing change?:**
n/a
=> Corrected go version command to use cut command

test/e2e/testsuites/gcsfuse_integration.go
- Making the test-case changes in CSI driver for the change in the gcsfuse - https://github.com/GoogleCloudPlatform/gcsfuse/pull/2853
- This started failing because of a bug fix in the gcsfuse - https://github.com/GoogleCloudPlatform/gcsfuse/pull/2822. The test failure was not because of a real failure but test strategy it uses to validate the kernel-list-cache feature.
=> Moving the DeleteDirTest of KernelListCache to different package

test/e2e/run-e2e-ci.sh
Adding the option to specify BUILD_GCSFUSE_FROM_SOURCE externally, to allow us to create different tests that build the driver with this option set.
=> Pass BUILD_GCSFUSE_FROM_SOURCE as EnvVar for custom driver testsuite.

test/e2e/testsuites/gcsfuse_integration.go, test/e2e/testsuites/gcsfuse_integration_file_cache.go, test/e2e/testsuites/gcsfuse_integration_file_cache_parallel_downloads.go
When executing this group of commands together when running the readonly testsuite, the command would return a blank string, instead of the go version. This is because although the command only specified `/` character once, it would get processed incorrectly down the line and would cause the final command to use `//` (double of the character) instead. 
Investigated `fmt.Sprintf` but it did not seem like the culprit. Issue could be on how we send the command to the pod instead. Breaking up command to increase readability and fix bug.
/cc @chrisThePattyEater
=> Execute gcsfuse testsuite version fetcher command separately.

test/e2e/testsuites/gcsfuse_integration.go
Remove unnecessary dashes on kernel list cache integration test mount options to fix test failures.
Followup of #443 .
=> Remove unnecessary dashes on kernel list cache integration test mount options.

test/e2e/testsuites/failed_mount.go
Fix gcsfuse integration failed mount due to non-existent bucket tests. GCSFuse attempts retries and returns different error types when using gRPC. Accounting for this change in the testsuite.
=> Fix gcsfuse integration failed mount due to non-existent bucket tests.

test/e2e/testsuites/failed_mount.go, test/e2e/testsuites/gcsfuse_integration.go
On  #443 and #448, we modified testsuite behavior for new versions, but these changes are not backwards compatible with older GKE versions. Adding backward compatibility for testsuite to fix managed TestGrid.
=> Add backward compatibility for testsuite to fix GKE Managed TestGrid.

test/e2e/testsuites/failed_mount.go
SkipCSIBucketAccessCheckAndInvalidVolumePrefix returns the error from GCSFuse when a bucket has an invalid name. This logic has to be updated to support more granular error messages and error codes for this scenario starting GCSFuse v2.5.0
Followup of #453
=> Fix failed mount due to invalid bucket name e2e tests.

test/e2e/testsuites/gcsfuse_integration.go
Add an integration test for gcsfuse `v2.9.0`, which includes a new flag, `enable-streaming-writes`. The flag is disabled by default in gcsfuse
=> add integration test for gcsfuse v2.9.0

test/e2e/testsuites/failed_mount.go
Update gcsfuse version that supports InvalidArgument error code. We know the version v2.9.0 starts supporting this new error code type, but we had changed it accidentally in #454
=> Update gcsfuse version that supports InvalidArgument error code to v2.9.0.

cmd/sidecar_mounter/gcsfuse_binary
Update gcsfuse_binary to v2.9.1 to address bug in v2.9.0
More details on [here](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v2.9.1)
=> Update gcsfuse_binary to v2.9.1

test/e2e/testsuites/gcsfuse_integration.go
This PR updates streaming writes e2e tests to fix execution of streaming writes e2e tests. 
Referenced the gcsfuse e2e test execution script [here](https://github.com/GoogleCloudPlatform/gcsfuse/blame/7bbde84a2502eec7c6792fceeafe89178b9b6d7e/tools/integration_tests/run_tests_mounted_directory.sh#L580) to update these tests.
=> Update streaming writes e2e tests

pkg/sidecar_mounter/sidecar_mounter_config.go, pkg/sidecar_mounter/sidecar_mounter_config_test.go
>
/kind bug
> /kind design
> /kind flake
Update port used by GCSFuse metrics endpoint to reduce likelyhood of running into port coflicts in #392
```release-note
Update port used by GCSFuse metrics endpoint to reduce port conflicts.
```
=> Update port used by GCSFuse metrics endpoint.

pkg/sidecar_mounter/sidecar_mounter.go
>
/kind bug
> /kind design
> /kind flake
When we disable metrics, we still enable the gke gcsfuse sidecar metrics collector server endpoint to collect metrics. The intended behavior is to disable all metrics serviced. 
Fixes #
Bug found while going through the code.
```release-note
Disable sidecar metrics server when metrics are disabled.
```
/cc @kislaykishore
=> Disable sidecar metrics server when metrics are disabled.

cmd/webhook/main.go, pkg/webhook/config.go, pkg/webhook/injection.go, pkg/webhook/injection_test.go, pkg/webhook/mutatingwebhook.go, pkg/webhook/mutatingwebhook_test.go, pkg/webhook/sidecar_spec.go
Added capability to provide metadata prefetch memory request and limits in pod spec to fuse csi annotations Additionally added unit tests verifying changes.
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This pr adds functionality to allow fuse driver users to provide custom metadata prefetch sidecar memory and limits. The changes add additional annotations and variables to extract prefetch limits and requests if provided and uses those values for the prefetch sidecar config if provided. Otherwise it uses default …
=> Added capability to provide metadata prefetch memory request and limits in pod spec

cmd/webhook/main.go, pkg/webhook/config.go, pkg/webhook/injection.go, pkg/webhook/injection_test.go, pkg/webhook/mutatingwebhook.go, pkg/webhook/mutatingwebhook_test.go, pkg/webhook/sidecar_spec.go
Revert "Merge pull request #472 from chrisThePattyEater/fuechr/metadata-prefetch-memory-override"
This reverts commit ac9dc7c5cacd37ca6987426e35180d24d1ce4b1a, reversing changes made to 7b906aa74326c1d900da329a4295dcc451515173.
>
> /kind bug
> /kind design
> /kind flake
Revert "Merge pull request #472 from chrisThePattyEater/fuechr/metadata-prefetch-memory-override", needed due to failing test cases
Fixes #
**Does this PR introduce a …
=> Revert "Merge pull request #472 from chrisThePattyEater/fuechr/metadata-prefetch-memory-override"

pkg/cloud_provider/auth/fake.go, pkg/cloud_provider/auth/token_manager.go, pkg/csi_driver/node.go, pkg/sidecar_mounter/sidecar_mounter.go, pkg/sidecar_mounter/sidecar_mounter_config.go, pkg/sidecar_mounter/sidecar_mounter_config_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
We need environment specific id provider to facilitate sandbox/staging testing.
Fixes #
Tested:
1) building and installing GCSFuse CSI on a test cluster and created 1) pod with hostnetwork 2) pod without hostnetwork.
2) e2e test 
```
make e2e-test E2E_TEST_USE_GKE_MANAGED_DRIVER=false E2E_TEST_BUILD_DRIVER=true E2E_TEST_FOCUS=should.successfully.mount.for.hostnetwork.enabled.pods …
```
=> Add identity provider into mount options

cmd/webhook/main.go, pkg/webhook/config.go, pkg/webhook/injection.go, pkg/webhook/injection_test.go, pkg/webhook/mutatingwebhook.go, pkg/webhook/mutatingwebhook_test.go, pkg/webhook/sidecar_spec.go
This reverts commit 6c9a97d82d78acf902381fb0bc87f8e3eba93ac2.
Additionally corrects the incorrect annotation redefinition in pr-/472
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This pr adds functionality to allow fuse driver users to provide custom metadata prefetch sidecar memory and limits. The changes add additional annotations and variables to extract prefetch limits and requests if provided and uses those values for the prefetch sidecar config if provided. Otherwise it uses default values
**Which issue(s) …
=> Reapply "Merge pull request #472 and correct annotation redfinition"

hack/utils/delete-generated-buckets.sh, test/e2e/specs/testdriver.go
>
/kind bug
> /kind design
> /kind flake
When running the e2e testsuite locally, sometimes you may want to terminate it early. If terminated suddenly, the buckets that were generated wont be deleted. Adding a script that can perform this cleanup.
```release-note
```
=> Add script to delete leaked autogenerated buckets.

test/e2e/utils/cluster.go, test/e2e/utils/handler.go
>
> /kind bug
> /kind design
> /kind flake
Skip mount options test for versions where mountOption length hasn't been extended. We are only going to add https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/503 into the 1.32 release, so we should skip for versions less than 1.32.
Fixes #
```release-note
Skip mount options test for versions where mountOption length hasn't been …
```
=> skip mountOptions test for versions where it is not supported

go.mod, pkg/cloud_provider/clientset/clientset.go, pkg/csi_driver/node.go, pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go, test/e2e/specs/specs.go, test/e2e/testsuites/volumes.go, vendor/golang.org/x/mod/LICENSE, vendor/golang.org/x/mod/PATENTS, vendor/golang.org/x/mod/semver/semver.go, vendor/modules.txt
>
/kind bug
> /kind design
> /kind flake
This PR makes sure latest version of driver is compatible with custom or outdated sidecar images.
Fixes #
Tested:
1. e2e test shows version filter works as expected.
```
make e2e-test E2E_TEST_USE_GKE_MANAGED_DRIVER=false E2E_TEST_BUILD_DRIVER=true E2E_TEST_FOCUS=should.gcsfuse.process.succeed.without.missing.flag.error.for.hostnetwork.pods.using.custom.sidecar.container.image …
```
=> Only pass identity provider mountOption for managed sidecar version >= v1.12.2-gke.0

test/e2e/testsuites/volumes.go, test/e2e/utils/handler.go
>
> /kind bug
> /kind design
> /kind flake
Violations details: {"[denied by autogke-disallow-hostnamespaces]":["enabling hostNetwork is not allowed in Autopilot."]}
Fixes #
```release-note
NONE
```
=> Skip tests for hostnetwork enabled pods on autopilot clusters

go.mod, pkg/cloud_provider/clientset/clientset.go, pkg/csi_driver/node.go, pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go, test/e2e/specs/specs.go, test/e2e/testsuites/volumes.go, vendor/golang.org/x/mod/LICENSE, vendor/golang.org/x/mod/PATENTS, vendor/golang.org/x/mod/semver/semver.go, vendor/modules.txt
Cherry pick of #520 on release-1.13.
#520: Only pass identity provider mountOption for managed sidecar version >= v1.12.2-gke.0
```release-note
Only pass identity provider mountOptions for managed sidecar version >= v1.12.2-gke.0
```
=> Automated cherry pick of #520: Only pass identity provider mountOption for managed sidecar version >= v1.12.2-gke.0

test/e2e/testsuites/volumes.go, test/e2e/utils/handler.go
Cherry pick of #530 on release-1.13.
#530: Skip tests for hostnetwork enabled pods on autopilot clusters
```release-note
NONE
```
=> Automated cherry pick of #530: Skip tests for hostnetwork enabled pods on autopilot clusters

cmd/csi_driver/main.go, deploy/base/node/node_setup.yaml, pkg/cloud_provider/clientset/clientset.go, pkg/cloud_provider/clientset/fake.go, pkg/csi_driver/gcs_fuse_driver_test.go, pkg/csi_driver/node.go, pkg/csi_driver/node_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Add a check for GKE metadata server label on node to fail MountVolume (NodePublishVolume) with an actionable error. The target scenario is when an user enabled Workload Identity on an existing cluster, but didn't update their node pool to use GKE metadata server. Currently, this error takes more effort to debug since NodePublishVolume still succeeds, but we would see R/W errors from the sidecar due to PermissionDenied as the default SA lacks the appropriate permission …
=> Fail NodePublishVolume with actionable error in case Workload Identity is not yet enabled on node level

cmd/csi_driver/main.go, deploy/base/node/node_setup.yaml, pkg/cloud_provider/clientset/clientset.go, pkg/cloud_provider/clientset/fake.go, pkg/csi_driver/gcs_fuse_driver_test.go, pkg/csi_driver/node.go, pkg/csi_driver/node_test.go
Cherry pick of #533 on release-1.13.
#533: Fail NodePublishVolume with actionable error in case Workload Identity is not yet enabled on node level
```release-note
Fail MountVolume with actionable error in case Workload Identity is not yet enabled on node level
```
=> Automated cherry pick of #533: Fail NodePublishVolume with actionable error in case Workload Identity is not yet enabled on node level

cmd/csi_driver/main.go, deploy/base/node/node_setup.yaml, pkg/cloud_provider/clientset/clientset.go, pkg/cloud_provider/clientset/fake.go, pkg/csi_driver/gcs_fuse_driver_test.go, pkg/csi_driver/node.go, pkg/csi_driver/node_test.go
Reverts GoogleCloudPlatform/gcs-fuse-csi-driver#548 as this is fixing verify test. I'll try chaining this with the PRs https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/556 in one cherry-pick PR.
=> Revert "Automated cherry pick of #533: Fail NodePublishVolume with actionable error in case Workload Identity is not yet enabled on node level"

cmd/csi_driver/Dockerfile, cmd/sidecar_mounter/Dockerfile, cmd/webhook/Dockerfile
>
/kind bug
> /kind design
> /kind flake
Bumps golang build version 1.22.4 -> 1.23.3 for the sidecar mounter, csidriver and webhook. This is needed to correct failures in louhi pipeline that prevent image for tage 1.3.6 to be created. The bug tracking these louhi failures can be found here https://b.corp.google.com/issues/411218927.
Fixes #411218927
```release-note
```
=> Bump golang build version 1.22.4 -> 1.23.3

pkg/csi_driver/controller.go, pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
When users try to use the same bucket in two different persistent volumes (same value for bucket handle field) and mount these pvs to the same node kubelet does not call node publish volume a second time it treats both volumes as the same which prevents containers from starting (the second volume is not mounted at the expected path). This is a limitation of the gcsfuse csi driver as described [here](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/t …
=> Allow multiple volume handles with different mount options

cmd/csi_driver/main.go, deploy/base/node/node.yaml, pkg/csi_driver/node.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
GCSFuse is designed around exporting metrics from the GCSFuse processes that runs on each sidecar, through node-server container, and going through GKE Metrics collector. Currently we do not have limits set on the number of metrics we can export. We can easily reach limits in the amount of metrics we can export and cause node-server to become unhealthy. Although the only symptom would be metrics not exporting, this would cause our SLOs to trigger on behavior that we …
=> Limit the maximum number of registered metric collectors.

cmd/csi_driver/main.go, deploy/base/node/node.yaml, pkg/csi_driver/node.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
Cherry pick of #547 on release-1.14.
#547: Limit the maximum number of registered metric collectors.
```release-note
Limit the maximum number of registered metric collectors.
```
=> Automated cherry pick of #547: Limit the maximum number of registered metric collectors.

pkg/sidecar_mounter/sidecar_mounter_config.go, pkg/sidecar_mounter/sidecar_mounter_config_test.go
>
/kind bug
> /kind design
> /kind flake
On #569 we enabled metrics by default by changing the value (passed when `disableMetrics` VolumeAttribute(VA) is not present) of the `disable-metrics-on-gke` mountOption (which are passed to the sidecar) from true to false. We also need to handle the defaulting behavior on the sidecar side. This PR enables metrics collection by default on the sidecar.
Currently the metrics collection is not set unless the `disableMetrics` VA is set. …
=> Enable metrics collection by default on gcsfusecsi sidecar.

pkg/sidecar_mounter/sidecar_mounter_config.go, pkg/sidecar_mounter/sidecar_mounter_config_test.go
Cherry pick of #574 on release-1.14.
#574: Enable metrics collection by default on gcsfusecsi sidecar.
```release-note
Enable metrics collection by default on gcsfusecsi sidecar.
```
=> Automated cherry pick of #574: Enable metrics collection by default on gcsfusecsi sidecar.

pkg/sidecar_mounter/sidecar_mounter_config.go, pkg/sidecar_mounter/sidecar_mounter_config_test.go
Reverts GoogleCloudPlatform/gcs-fuse-csi-driver#574 until GCSFuse e2e test failures are resolved.
Issue is visible on https://github.com/GoogleCloudPlatform/gcsfuse/pull/3239 as presubmit e2e tests fail.
=> Revert "Enable metrics collection by default on gcsfusecsi sidecar."

cmd/csi_driver/main.go, cmd/sidecar_mounter/main.go, pkg/cloud_provider/clientset/clientset.go, pkg/cloud_provider/clientset/fake.go, pkg/csi_driver/gcs_fuse_driver.go, pkg/csi_driver/node.go, pkg/csi_driver/node_test.go, pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go, pkg/sidecar_mounter/sidecar_mounter_config.go, test/e2e/specs/specs.go, test/e2e/specs/testdriver.go, test/e2e/testsuites/mount.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR bumped gcsfuse binary to v2.12.0-gke-0, where the the new two mountOptions start to be supported. Note that gcsfuse receives these flags but will not turn on the default values until v3.
**Summary of changes:**
As part of GCSFuse's intelligent defaults, new mountOption flags are supported: --machine-type and --disable-autoconfig.
We want to pass these two flags over from the driver to GCSFuse in the following mechanism:
1. --machine-type: The driver has …
=> Pass --machine-type and --disable-autoconfig flags from driver to gcsfuse

pkg/sidecar_mounter/sidecar_mounter_config.go, pkg/sidecar_mounter/sidecar_mounter_config_test.go
Redoes GoogleCloudPlatform/gcs-fuse-csi-driver#574
This change temporarily reverted on #574 due to GCSFuse bug. This bug is now fixed on GCSFuse HEAD and we are pending next GCSFuse release to merge this change.
*Note*: Do not merge until GCSFuse fix (GCSFuse v2.12) is merged on CSI main branch.
=> Redo "Enable metrics collection by default on gcsfusecsi sidecar."

test/e2e/testsuites/mount.go
…on is unknown
>
> /kind bug
> /kind design
> /kind flake
Skip E2E tests for gcsfuse's defaulting flags while we don't have a released sidecar version with gcsfuse v2.12 (starting version for the new flags' support). 
We have a sidecar version filter for this feature. The version is currently using a placeholder sidecar version of v1.99.0-gke.0, so related E2E tests will fail expectedly. We'll run these E2E tests once we've finished the first round of release and have a min sidecar version to replace the …
=> Skip E2E tests for gcsfuse's defaulting flags while min sidecar version is not known

test/e2e/testsuites/mount.go
>
> /kind bug
> /kind design
> /kind flake
Skip E2E test for hostnetwork feature. This is failing after we've rolled back the feature. We can re-enable the test once it's rolled out again.
Fixes #
```release-note
```
=> Skip hostnetwork e2e tests

pkg/csi_driver/node.go, pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go, test/e2e/testsuites/mount.go, test/e2e/utils/cluster.go, test/e2e/utils/handler.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
We have minimum sidecar version that supports the feature now (1.15.1-gke.0), so we can update the version filter logic to use this version. The PR also enables the existing E2E tests for this feature with a 1.33 cluster version filter.
Fixes #
```release-note
Add minimum sidecar version for intelligent defaults on high-performance machine types and …
```
=> Add minimum sidecar version for intelligent defaults and enable E2E tests

pkg/csi_driver/node.go, pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go, test/e2e/testsuites/mount.go, test/e2e/utils/cluster.go, test/e2e/utils/handler.go
Cherry pick of #602 on release-1.15.
#602: Add minimum sidecar version for intelligent defaults and enable E2E tests
```release-note
Add minimum sidecar version for intelligent defaults on high-performance machine types and enable corresponding E2E tests
```
=> Automated cherry pick of #602: Add minimum sidecar version for intelligent defaults and enable E2E tests

pkg/csi_driver/utils.go, test/e2e/testsuites/mount.go, test/e2e/utils/handler.go
Fix build issues with E2E tests while enabling e2e tests for high-performance machine types.
>
> /kind bug
> /kind design
> /kind flake
https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/602 introduced a build error with E2E test, so this PR is meant to fix that. I also modified the test-skip logic to skip managed drivers for now since the target tests for intelligent defaults will still fail for managed drivers until we complete the next release and the minimum sidecar version in …
=> Fix build issues with E2E tests

pkg/csi_driver/utils.go, test/e2e/testsuites/mount.go, test/e2e/utils/handler.go
Cherry pick of #606 on release-1.15.
#606: Fix build issues with E2E tests
```release-note
Fix build issues with E2E tests while enabling e2e tests for high-performance machine types.
```
=> Automated cherry pick of #606: Fix build issues with E2E tests

pkg/cloud_provider/clientset/clientset.go
>
> /kind bug
> /kind design
> /kind flake
Cherrypick/backport informer filtering to GKE versions 1.31.
Original PR: https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/413
Fixes #
```release-note
NONE
```
=> Filtering informerFactory to return relevant PodSpec information [Cherrypick main --> 1.8]

test/e2e/utils/handler.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Previously, we [skipped](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/606) E2E tests on high-performance machine types for our managed test grid since our 1.33 testgrid was on an older GKE version with a placeholder sidecar version.  Now the testgrid has been updated to use [1.33.0-gke.2248000](https://screenshot.googleplex.com/JjuWxpnLfkdzN2Y), which is [mapped](https://paste.googleplex.com/4726408225751040) to [our 1.15.2 upstream release …
=> Re-enable E2E tests for defaults on high-performance machine types on managed drivers

pkg/sidecar_mounter/sidecar_mounter_config.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Cherrypick #615 to release-1.15
Fixes #
```release-note
log error to unlink socket path only if the error is not ENOENT
```
=> Cherrypick #615 to release-1.15

cmd/sidecar_mounter/gcsfuse_binary
Cherry pick of #654 on release-1.15.
#654: Bump gcsfuse to v2.12.2 for CVE fix
```release-note
Bump gcsfuse to v2.12.2 for CVE fix
```
=> Automated cherry pick of #654: Bump gcsfuse to v2.12.2 for CVE fix

cmd/sidecar_mounter/main.go, docs/troubleshooting.md, pkg/csi_driver/node.go, pkg/csi_driver/utils.go, pkg/csi_mounter/csi_mounter.go, pkg/sidecar_mounter/sidecar_mounter.go, pkg/util/util.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR allows the GCSFuse CSI Driver to handle Node restarts. We are currently seeing more demand for this feature as the restarts become increasingly common the scale of the cluster increases. Certain nodes (e.g. TPU and GPU VMs) perform restarts for more scenarios compared to a traditional GKE node/nodepool (e.g. host error, maintenance preemption, etc.)
**Restart scenarios tested**:
We've manually verified select features of the GCSFuse CSI Driver against node …
=> Add support for node restarts.

docs/troubleshooting.md, pkg/csi_driver/node.go, pkg/csi_mounter/csi_mounter.go, pkg/sidecar_mounter/sidecar_mounter.go, pkg/util/util.go, pkg/util/util_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR increases readability for both dev team to develop and triage customer cases. This PR also includes updates to troubleshooting docs for TSE and customers.
Fixes #
```release-note
None
```
=> Clean up node restart support logging and comments.

cmd/sidecar_mounter/gcsfuse_binary, test/e2e/testsuites/gcsfuse_integration.go
Reverts GoogleCloudPlatform/gcs-fuse-csi-driver#757
Now several other tests are failing. I ran streaming_writes tests  but now metrics and some other tests are failing too. Will debug locally, then remerge.
=> Revert "bump to gcsfuse v3 and add new flag to streaming_writes tests"

pkg/cloud_provider/storage/storage.go, test/README.md, test/e2e/e2e_test.go, test/e2e/main.go, test/e2e/run-e2e-ci.sh, test/e2e/run-e2e-local.sh, test/e2e/specs/testdriver.go, test/e2e/testsuites/gcsfuse_integration.go, test/e2e/testsuites/gcsfuse_integration_file_cache.go, test/e2e/testsuites/gcsfuse_integration_file_cache_parallel_downloads.go, test/e2e/utils/handler.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This pr introduces support for Zonal Buckets during e2e gcsfuse tests. Specifically it makes it so when passing the optional argument ENABLE_ZB the bucket created during tests is set to be a ZB created in the region provided -c. For example if the regional cluster was created in us-central1 then the zb would be created in us-central1-c. US-central1-c is the only zone we currently support for zb e2e testing.
Fixes #
**Special notes for …
=> Added ZB support during e2e tests

test/e2e/e2e_test.go
>
> /kind bug
> /kind design
> /kind flake
Summary:
Reinstates zb flag , we had disabled due to incorrect passing of value.
Problem:
The issue was that package-level variables in Go are initialized during package loading, which happens before flag.Parse() is called.
This meant that when we dereferenced our CLI flag (e.g., *enableZB) during package initialization — for example, by assigning it to a var at the top level — it captured the default value, not the one passed via command-line arguments.
Even though …
=> Re-apply zb flag

renovate.json
Renovate is adding additional toil to release czar and cluttering PR count.
Will also close all PRs created and not merged by renovate-bot 
Reverts GoogleCloudPlatform/gcs-fuse-csi-driver#502
=> Stop testing renovate

pkg/csi_driver/node.go, pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go, test/e2e/testsuites/failed_mount.go, test/e2e/testsuites/mount.go, test/e2e/utils/handler.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
We need to specify the minimum sidecar version that supports the host network ksa token feature. It is needed because sidecars with versions lower than the min is not compatible with the (internal only) mount options.
This PR also skips OSS tests for clusters without support for native sidecars.
Fixes #
Ran e2e tests on 1.28 cluster and confirmed it is not failing any more.
```
make e2e-test …
```
=> Update token server sidecar min version

pkg/csi_driver/node.go, pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go, test/e2e/testsuites/failed_mount.go, test/e2e/testsuites/mount.go, test/e2e/utils/handler.go
Cherry pick of #867 on release-1.17.
#867: Update token server sidecar min version
```release-note
NA
```
=> Automated cherry pick of #867: Update token server sidecar min version

docs/troubleshooting.md, pkg/csi_driver/node.go, pkg/csi_mounter/csi_mounter.go, pkg/sidecar_mounter/sidecar_mounter.go, pkg/util/util.go, pkg/util/util_test.go
Cherrypick #668 to release-1.14: Clean up node restart support logging and comments.
Cherry pick to GKE 1.32.x
=> Cherrypick #668 to release-1.14: Clean up node restart support logging and comments.

cmd/sidecar_mounter/gcsfuse_binary
Cherry pick of #874 on release-1.17.
#874: Update gcsfuse binary patch to resolve vulnerability
```release-note
NONE
```
=> Automated cherry pick of #874: Update gcsfuse binary patch to resolve vulnerability

pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go
>
/kind bug
> /kind design
> /kind flake
This PR adds gke.gcr.io as a managed sidecar image registry format. We recently found out some customers using managed sidecar has gke.gcr.io as the registry name instead of "`.*-artifactregistry.gcr.io/gke-release/.*"
Fixes #
1. Valid gcr host names are retrieved from go/gke-release-infra#gcr-container-images
2. Also updated min sidecar version for token server so that we support users with …
=> Add gke.gcr.io as a managed sidecar image registry format

cmd/sidecar_mounter/gcsfuse_binary, test/e2e/testsuites/gcsfuse_integration.go, test/e2e/testsuites/gcsfuse_integration_file_cache.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Bumps GCSFuse binary to  v3.1.0
Fixes #
Tested via: 
```
gcloud container clusters create test-gcsfusev3-new \
--zone=us-central1-a \
--workload-pool=amacaskill-gke-dev.svc.id.goog --machine-type=c3-standard-44
gcloud container clusters get-credentials test-gcsfusev3-new --zone us-central1-a
make build-image-and-push-multi-arch REGISTRY=us-central1-docker.pkg.dev/amacaskill-gke-dev/csi-dev …
```
=> release gcsfuse 3.1.0 and enable inactive_stream_timeout tests

pkg/sidecar_mounter/sidecar_mounter.go
Cherry pick of #896 on release-1.17.
#896: Add filter for killed process from GCSFuse.
```release-note
The error encounter `signal: killed` when ending gcsfusecsi will be degraded from an error to a info log.
```
=> Automated cherry pick of #896: Add filter for killed process from GCSFuse.

test/e2e/e2e_test.go, test/e2e/main.go, test/e2e/run-e2e-ci.sh, test/e2e/run-e2e-local.sh
>
> /kind bug
> /kind design
> /kind flake
Recently we added tests to our tests grid that incorporate the new zonal bucket feature, unfortunately it seems that one of the flags being parsed defaults to false and never gets updated. This means that tests ran do not actually run using ZB. This fix implements a separate flag similare to other ones in the same file to ensure there is no run time discrepancies. 
Fixes #
How was this tested
make …
=> Fix for disabled zb test

test/e2e/specs/testdriver.go
>
> /kind bug
> /kind design
> /kind flake
This pr implements a change relating to failing tests introduced during the enablement of gcsfusexzonal buckets tests.
The change introduced in commit -  7753a057a0dce11582d8453414712a99d7bd26e0
This commit disabled the only-dir mount option (a flag used to communicate to gcsfuse that we have mounted our bucket in a subdirectory) for zb tests, this is needed because as mentioned in this ticket gcsfuse team does not currently support it …
=> ZB Test refactoring

pkg/csi_driver/node.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
The logs get printed on every node publish call per volume
```release-note
reduce verbosity of logs for hostnetwork node publish code path
```
=> reduce verbosity of logs for hostnetwork node publish code path

pkg/csi_driver/utils.go
Cherry pick of #908 on release-1.17.
#908: Downgrade bootstrap config error to warning
```release-note
```
=> Automated cherry pick of #908: Downgrade bootstrap config error to warning

cmd/sidecar_mounter/gcsfuse_binary
Cherry pick of #921 on release-1.17.
#921: bump gcsfuse version to v3.2
```release-note
Bump GCSFuse version to v3.2
```
=> Automated cherry pick of #921: bump gcsfuse version to v3.2

examples/gcsfuse-profiles/pv-pvc.yaml, pkg/scanner/scanner.go, pkg/scanner/scanner_test.go
/kind feature
This PR builds on top of the existing Bucket Scanner controller skeleton (https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/948) within the GCSFuse CSI driver. This controller watches PersistentVolumes (PVs) managed by `gcsfuse.csi.storage.gke.io` and, when relevant, performs simulated metadata scans on the associated GCS buckets. The results are stored as annotations on the PV.
Key features implemented in this PR:
*   **PV Event Handling**: Reacts to Add and Delete PV events.
*   **Relevance Checks**:
*   Ensures the PV uses the `gcsfuse.csi.storage.gke.io` driver.
*   Verifies the StorageClass has a valid `workloadType` parameter (`inference`, `training`, or `checkpointing`).
*   Implements …
=> Bucket scanner controller - PersistentVolume creation trigger

cmd/sidecar_mounter/gcsfuse_binary, test/e2e/testsuites/gcsfuse_integration.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Release GCSFuse v3.3.0.
Fixes #
Successful buffered read test run: https://paste.googleplex.com/5808318014685184
GCSFuse buffered read original tests can be found [here](https://github.com/GoogleCloudPlatform/gcsfuse/tree/94e4ade71cfa056bc3dd18a573bfbbb7cc4ae765/tools/integration_tests/buffered_read)
Testing setup:
```
gcloud container clusters create test-gcsfusev3-new \
--zone=us-central1-a \ …
```
=> Release GCSFuse 3.3.0 and enable buffered_read tests

examples/gcsfuse-profiles/pv-pvc-deployment.yaml, pkg/scanner/scanner.go, pkg/scanner/scanner_test.go
This PR enhances the Bucket Scanner controller within the GCSFuse CSI driver by introducing a Pod creation trigger and a scheduling gate mechanism. Instead of only reacting to PV events, the controller now watches for the creation of Pods labeled with `gke-gcsfuse/profile-managed: "true".`
This PRs is part of a chain of previous PRs to implement the bucket scanner controller:
* https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/948
* https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/953
New Pods with this label are expected to start with a scheduling gate `gke-gcsfuse/bucket-scan-pending`. The controller will:
* **Watch Pods**: Identify new Pods with the label and scheduling …
=> Bucket scanner controller - Pod creation trigger

test/e2e/testsuites/gcsfuse_integration.go
>
> /kind bug
> /kind design
> /kind flake
Make sure v3.3.0 integration tests clone gcsfuse from v3.3.0_release branch. GCSFuse team recently pushed a only_dir related test fix to the branch. We won't be able to pick it up if we clone from v3.3.0 tag.
Fixes #
```release-note
NA
```
=> Make gcsfuse integration tests run from head of branch for v3.3.0+

cmd/csi_driver/main.go, cmd/sidecar_mounter/main.go, deploy/base/node/node.yaml, pkg/cloud_provider/auth/fake.go, pkg/cloud_provider/auth/token_manager.go, pkg/cloud_provider/auth/token_sources.go, pkg/cloud_provider/storage/fake.go, pkg/cloud_provider/storage/storage.go, pkg/csi_driver/controller.go, pkg/csi_driver/gcs_fuse_driver.go, pkg/csi_driver/node.go, pkg/csi_driver/utils.go, pkg/csi_driver/utils_test.go, pkg/sidecar_mounter/sidecar_mounter.go, pkg/sidecar_mounter/sidecar_mounter_config.go, pkg/util/util.go, pkg/webhook/mutatingwebhook.go, pkg/webhook/sidecar_spec.go, test/e2e/specs/specs.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
The PR performs bucket access check in GCS Fuse sidecar. This check is currently performed in CSI node driver but that consumes additional STS quota hence it is being moved to sidecar. The STS quota benefits can be seen only for Workload Identity pods while HostNetwork pods will see ad additional STS quota request per pod.
Since the bucket access check is being performed in sidecar with this PR it can be skipped in node by setting `--skipCSIBucketAccessCheck=true` …
=> Add retry logic while fetching STS token in sidecar mounter

Makefile, cloudbuild-build-image.yaml, test/e2e/testsuites/gcsfuse_integration.go, test/e2e/testsuites/gcsfuse_integration_file_cache.go, test/e2e/testsuites/gcsfuse_integration_file_cache_parallel_downloads.go
>
/kind bug
> /kind design
> /kind flake
https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/commit/951265546d33fd1081b6f1bbdced35d74fdd6ddd#r166532713 broke running GCSFuse integration tests when driver was built/installed with `BUILD_FROM_GCSFUSE_SOURCE=true`. This is because the change introduced a versioning check that panics when `BUILD_FROM_GCSFUSE_SOURCE=true`. More details in  this comment: https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/commit/951265546d33fd1081b6f1bbdced35d74fdd6dd …
=> fix BUILD_FROM_GCSFUSE_SOURCE that was broken by previous PR

test/e2e/testsuites/gcsfuse_integration.go, test/e2e/testsuites/gcsfuse_integration_file_cache.go, test/e2e/testsuites/gcsfuse_integration_file_cache_parallel_downloads.go, test/e2e/utils/utils.go, test/e2e/utils/utils_test.go
>
/kind bug
> /kind design
> /kind flake
Update gcsfuse branch to use branch if it has gke in the version. This was missed in https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/980. Added unit test to make sure its working properly, and tested manually
Test both build from source, and build from a particullar gcsfuse tag: 
```
gcloud container clusters create test-gcsfuse-8 \
--zone=us-central1-a \
--workload-pool=amacaskill-gke-dev.svc.id.goog --machine-type=n2-standard-8
gcloud container …
```
=> update gcsfuse branch to use branch if it has gke in the version

cmd/sidecar_mounter/gcsfuse_binary, pkg/sidecar_mounter/sidecar_mounter_config.go, pkg/sidecar_mounter/sidecar_mounter_config_test.go, test/e2e/specs/specs.go, test/e2e/testsuites/mount.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Release GCSFuse v3.4.0 and dis-allow unsupported 'profile' flag which is included in 3.4
Fixes #
Testing setup
```
gcloud container clusters create gcsfuse-cluster     --workload-pool=fuechr-gke-dev.svc.id.goog --machine-type=n2-standard-8 --zone us-central1-c
make build-image-and-push-multi-arch REGISTRY=gcr.io/fuechr-gke-dev STAGINGVERSION=3.4
make install REGISTRY=gcr.io/fuechr-gke-dev …
```
=> Release GCSFuse 3.4.0 and disallow profile flag

cmd/csi_driver/Dockerfile, cmd/metadata_prefetch/Dockerfile, test/e2e/utils/handler.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes CVE-2025-9230, CVE-2025-9232 and skip profile test for managed
- Updated debian package to [v1.0.5](https://pantheon.corp.google.com/artifacts/docker/gke-release/us/us.gcr.io/debian-base/sha256:42340af792a01e81a1122a06a248a44884e6669f8db2210da42321a37a7a5bbd?e=13802955&mods=logs_tg_prod) needed to fix vulnerabilities for release 1.19.0
- Needed to fix failing tests on managed test grid that have yet to pick up latest changes from said release
**Which issue(s) …
=> Fix CVE-2025-9230, CVE-2025-9232 and skip profile test for managed

cmd/csi_driver/Dockerfile, cmd/metadata_prefetch/Dockerfile, test/e2e/utils/handler.go
Cherry pick of #988 on release-1.19.
#988: Fix CVE-2025-9230, CVE-2025-9232 and skip profile test for managed
```release-note
NONE
```
=> Automated cherry pick of #988: Fix CVE-2025-9230, CVE-2025-9232 and skip profile test for managed

Makefile, cloudbuild-build-image.yaml, cloudbuild-install.yaml, cloudbuild-uninstall.yaml, deploy/base/setup/csi_driver.yaml, docs/development.md, docs/installation.md, docs/oss-k8s-e2e-setup.md, pkg/cloud_provider/auth/token_sources.go, pkg/cloud_provider/metadata/fake.go, pkg/sidecar_mounter/sidecar_mounter.go, pkg/util/util.go, pkg/util/util_test.go, pkg/webhook/mutatingwebhook.go, pkg/webhook/sidecar_spec.go, pkg/webhook/sidecar_spec_test.go, test/e2e/specs/specs.go
Cherry pick of #975 on release-1.19.
#975: Add support and documentation for running GCSFuse CSI Driver on OSS K8s
```release-note
Add support and documentation for running GCSFuse CSI Driver on OSS K8s
```
=> Automated cherry pick of #975: Add support and documentation for running GCSFuse CSI Driver on OSS K8s

pkg/webhook/mutatingwebhook.go, pkg/webhook/sidecar_spec.go
Cherry pick of #989 on release-1.19.
#989: add host network restriction for SA volume injection
```release-note
NONE
```
=> Automated cherry pick of #989: add host network restriction for SA volume injection
